export const tradeServicesMap = {
  "Alarm / Security Services": ["Alarm / Security Services", "Alarm"],
  Builder: [
    "Builder",
    "Building Construction",
    "House Extension",
    "Loft Conversion",
    "Bricklaying",
    "Structural Repairs",
    "Building / Home Improvement Services",
  ],
  "Carpet Fitting": [
    "Carpet",
    "Carpet Fitting",
    "Carpet Installation",
    "Carpet Removal",
    "Flooring",
    "Vinyl Flooring",
    "Rug Installation",
    "Carpets / Flooring",
  ],
  "Carpets / Flooring": ["Carpets / Flooring"],
  "Driveways/Patios": [
    "Patio",
    "Driveway",
    "Driveways",
    "Patios",
    "Driveways/Patios",
    "Driveways / Patios",
    "Driveway Paving",
    "Patio Installation",
    "Block Paving",
    "Concrete Driveways",
    "Resin Driveways",
  ],
  Electrician: [
    "Electrician",
    "Electrical Wiring",
    "Light Installation",
    "Socket Repair",
    "Fuse Box Upgrade",
    "Circuit Installation",
    "Electrical",
  ],
  Gardener: [
    "Garden",
    "Gardener",
    "Lawn Mowing",
    "Gardening",
    "Garden Maintenance",
    "Hedge Trimming",
    "Planting",
    "Tree Pruning",
    "Landscaping",
  ],
  Joiner: [
    "Joiner",
    "Woodworking",
    "Furniture Making",
    "Cabinet Installation",
    "Door Fitting",
    "Staircase Installation",
  ],
  "Painter/Decorator": [
    "Decorator",
    "Painter",
    "Paint",
    "Painting",
    "Internal Painting",
    "External Painting",
    "Decorating",
    "Wall Coating",
    "Wallpaper Installation",
  ],
  Plasterer: [
    "Plasterer",
    "Plastering",
    "Wall Smoothing",
    "Skim Coating",
    "Ceiling Plastering",
    "Plaster Repair",
  ],
  Plumber: [
    "Plumber",
    "Plumbing",
    "Leak Repair",
    "Pipe Installation",
    "Water Heater Repair",
    "Drain Cleaning",
    "Toilet Repair",
  ],
  Roofer: [
    "Roofer",
    "Roofing",
    "Roof Repairs",
    "Gutter Cleaning",
    "Flat Roofing",
    "Chimney Repairs",
    "Slate Roof Installation",
  ],
  Tiler: [
    "Tiler",
    "Tiling",
    "Tile Installation",
    "Floor Tiling",
    "Wall Tiling",
    "Grouting",
    "Bathroom Tiling",
  ],
  Welder: [
    "Welding",
    "Weld",
    "Welder",
    "Metal Fabrication",
    "Gate Welding",
    "Fence Repair",
    "Steel Structure Welding",
    "Pipe Welding",
  ],
};
