export const tradeServicesMap = {
  Builder: [
    "Building Construction",
    "House Extension",
    "Loft Conversion",
    "Bricklaying",
    "Structural Repairs",
  ],
  "Carpet Fitting": [
    "Carpet Installation",
    "Carpet Removal",
    "Flooring",
    "Vinyl Flooring",
    "Rug Installation",
  ],
  "Driveways/Patios": [
    "Driveway Paving",
    "Patio Installation",
    "Block Paving",
    "Concrete Driveways",
    "Resin Driveways",
  ],
  Electrician: [
    "Electrical Wiring",
    "Light Installation",
    "Socket Repair",
    "Fuse Box Upgrade",
    "Circuit Installation",
  ],
  Gardener: [
    "Lawn Mowing",
    "Garden Maintenance",
    "Hedge Trimming",
    "Planting",
    "Tree Pruning",
    "Landscaping",
  ],
  Joiner: [
    "Woodworking",
    "Furniture Making",
    "Cabinet Installation",
    "Door Fitting",
    "Staircase Installation",
  ],
  "Painter/Decorator": [
    "Painter",
    "Paint",
    "Painting",
    "Internal Painting",
    "External Painting",
    "Decorating",
    "Wall Coating",
    "Wallpaper Installation",
  ],
  Plasterer: [
    "Plastering",
    "Wall Smoothing",
    "Skim Coating",
    "Ceiling Plastering",
    "Plaster Repair",
  ],
  Plumber: [
    "Plumbing",
    "Leak Repair",
    "Pipe Installation",
    "Water Heater Repair",
    "Drain Cleaning",
    "Toilet Repair",
  ],
  Roofer: [
    "Roof Repairs",
    "Gutter Cleaning",
    "Flat Roofing",
    "Chimney Repairs",
    "Slate Roof Installation",
  ],
  Tiler: [
    "Tiling",
    "Tile Installation",
    "Floor Tiling",
    "Wall Tiling",
    "Grouting",
    "Bathroom Tiling",
  ],
  Welder: [
    "Metal Fabrication",
    "Gate Welding",
    "Fence Repair",
    "Steel Structure Welding",
    "Pipe Welding",
  ],
};
