export const traderCategoryOptions = [
  {
    value: "air_conditioning_ventilation",
    label: "Air Conditioning & Ventilation",
  },
  { value: "alarms_security", label: "Alarms & Security" },
  { value: "architectural_services", label: "Architectural Services" },
  { value: "artificial_grass", label: "Artificial Grass" },
  { value: "bathrooms", label: "Bathrooms" },
  { value: "blacksmith_ironwork", label: "Blacksmith / Ironwork" },
  {
    value: "boiler_installation_repairs",
    label: "Boiler Installation / Repairs",
  },
  { value: "builder", label: "Builder" },
  {
    value: "carpet_upholstery_cleaning",
    label: "Carpet & Upholstery Cleaning",
  },
  { value: "carpet_fitters", label: "Carpet Fitters" },
  { value: "central_heating_boilers", label: "Central Heating & Boilers" },
  { value: "chimney_services", label: "Chimney Services" },
  { value: "chimney_sweep_repairs", label: "Chimney Sweep & Repairs" },
  {
    value: "conservatories_garden_rooms",
    label: "Conservatories & Garden Rooms",
  },
  { value: "curtain_blind_fitters", label: "Curtain & Blind Fitters" },
  { value: "damp_proofing", label: "Damp Proofing" },
  { value: "decking", label: "Decking" },
  { value: "door_lock_installers", label: "Door & Lock Installers" },
  { value: "domestic_cleaning", label: "Domestic Cleaning" },
  { value: "drainage_blockages", label: "Drainage & Blockages" },
  { value: "driveways_patios", label: "Driveways & Patios" },
  { value: "electrician", label: "Electrician" },
  { value: "emergency_roofing_repairs", label: "Emergency Roofing Repairs" },
  { value: "end_of_tenancy_cleaning", label: "End of Tenancy Cleaning" },
  {
    value: "exterior_pressure_cleaning",
    label: "Exterior / Pressure Cleaning",
  },
  { value: "exterior_wall_insulation", label: "Exterior Wall Insulation" },
  { value: "extensions_conversions", label: "Extensions & Conversions" },
  { value: "fascia_soffits_guttering", label: "Fascia, Soffits & Guttering" },
  { value: "fencing_gates", label: "Fencing & Gates" },
  { value: "fireplace_log_burners", label: "Fireplace / Log Burners" },
  {
    value: "flooring_fitters",
    label: "Flooring Fitters (Wood, Laminate, Vinyl)",
  },
  { value: "garage_conversions", label: "Garage Conversions" },
  { value: "garage_doors", label: "Garage Doors" },
  { value: "garden_design", label: "Garden Design" },
  { value: "gardening_maintenance", label: "Gardening / Maintenance" },
  {
    value: "glass_double_glazing_repairs",
    label: "Glass / Double Glazing Repairs",
  },
  { value: "gutter_cleaning", label: "Gutter Cleaning" },
  { value: "home_it_telecoms", label: "Home IT & Telecoms" },
  { value: "insulation", label: "Insulation" },
  { value: "interior_design_support", label: "Interior Design Support" },
  { value: "joinery_carpentry", label: "Joinery & Carpentry" },
  { value: "kitchens", label: "Kitchens" },
  { value: "landscaping", label: "Landscaping" },
  { value: "lighting_installation", label: "Lighting Installation" },
  { value: "loft_conversions", label: "Loft Conversions" },
  { value: "outdoor_lighting", label: "Outdoor Lighting" },
  { value: "painting_decorating", label: "Painting & Decorating" },
  { value: "pest_control", label: "Pest Control" },
  { value: "plastering", label: "Plastering" },
  { value: "plumber", label: "Plumber" },
  { value: "powered_access_lifts", label: "Powered Access / Lifts" },
  {
    value: "renewable_energy",
    label: "Renewable Energy (Solar, EV Charging)",
  },
  { value: "roofing", label: "Roofing (Flat / Pitched / Repairs)" },
  { value: "roughcasting_rendering", label: "Roughcasting & Rendering" },
  { value: "scaffolders", label: "Scaffolders" },
  { value: "scaffolding", label: "Scaffolding" },
  { value: "smart_home_systems", label: "Smart Home Systems" },
  { value: "stonework_masonry", label: "Stonework & Masonry" },
  { value: "tiling", label: "Tiling" },
  {
    value: "tool_hire_accessory_supply",
    label: "Tool Hire / Accessory Supply",
  },
  { value: "tree_surgery", label: "Tree Surgery" },
  { value: "tv_aerials_satellite", label: "TV Aerials / Satellite" },
  { value: "underfloor_heating", label: "Underfloor Heating" },
  {
    value: "upvc_windows_window_fitters",
    label: "UPVC Windows / Window Fitters",
  },
  {
    value: "wardrobes_storage_solutions",
    label: "Wardrobes & Storage Solutions",
  },
  { value: "waste_clearance", label: "Waste Clearance" },
  { value: "weatherproof_coatings", label: "Weatherproof Coatings" },
  {
    value: "window_fitters_upvc_windows",
    label: "Window Fitters / UPVC Windows",
  },
];
