# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Build the app
    - name: Build the app
      run: |
        npm run build

    # Skip tests if not needed
    # Comment out the test step if you want to skip it
    - name: Run tests (optional)
      if: ${{ github.event_name != 'push' || (github.ref != 'refs/heads/main') }}
      run: |
        npm run test

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./build
